### ISSUE TITLE
Error: Parameters fail (caused by change in puppet 4 interpreting empty strings as true)

### ISSUE THREAD

**Issue by bobweston** [example42/puppet-monit#17]
When provisioning with Puppet4, I'm getting the following error:

Error: Parameter source failed on File[monit.dir]: Cannot use relative URLs '' at /tmp/vagrant-puppet/environments/puppet/modules/monit/manifests/init.pp:497

The module has worked with puppet 3.x. But I'm not able to use it with puppet 4. Any thoughts on a work around? I really appreciate any help or suggestions you can provide.

To be clear, I haven't specified that parameter at all. But the bit at the top of the init.pp file indicates that it is an optional parameter.
<pre>
  [*source*]
   Sets the content of source parameter for main configuration file
   If defined, monit main config file will have the param: source => $source
   Can be defined also by the (top scope) variable $monit_source

 [*source_dir*]
   If defined, the whole monit configuration directory content is retrieved
   recursively from the specified source
   (source => $source_dir , recurse => true)
   Can be defined also by the (top scope) variable $monit_source_dir
</pre>
But it seems that by not declaring that parameter, the module takes that as defining it as an empty string.

It would seem that at the very least, the docs should be updated to reflect that this is a required parameter.

Thank you. I really do appreciate your work on these modules.

**Comment by bobweston** [comment]
Ok. It appears that a work around for this is to set the parameter to false:
<pre>
class {'::monit':
    source_dir => false,
}
</pre>

I'm leaving this here in the event that anyone else runs into this problem using this module with puppet4. (fwiw, it ran fine in puppet 3.8)

**Comment by bobweston** [comment]
One more update on this. The reason this breaks is a change in puppet 4. Empty strings are now interpreted as true, not false.

https://docs.puppetlabs.com/puppet/latest/reference/experiments_future.html#empty-strings-in-boolean-context-are-true

An alternative work around that I'm testing is to set  source_dir to false in my hiera file.

monit::source_dir: false

**Comment by alvagante** [comment]
The referenced commit should fix, please let me know

**Comment by bobweston** [comment]
sorry for the delay. Yep. that works. Thank you.

**Comment by dagobert** [comment]
Can you release the master as a new version on forge.puppetlabs.com

**Comment by alvagante** [comment]
Just pushed v2.0.18
